version: '3'

services:
  ci-build:
    image: microsoft/aspnetcore-build:1.1.2
    volumes:
      - .:/src
    working_dir: /src
    command: /bin/bash -c "dotnet restore ./chapter5.sln && dotnet publish ./chapter5.sln -c Release -o ./obj/Docker/publish"
