version: '3'

services:
  shoppingcart:
    image: shoppingcart
    build:
      context: ./ShoppingCart
      dockerfile: Dockerfile
    depends_on:
      - sql.data

  sql.data:
    image: microsoft/mssql-server-linux

  eventstore:
    image: eventstore/eventstore
