version: '3'

services:
  shoppingcart:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - ConnectionString=Server=sql.data;Database=ShoppingCart;User Id=sa;Password=Pass@word
      - EventStoreConnectionString=ConnectTo=tcp://admin:changeit@eventstore:1113/
      - EventStoreType=EventStore
      - ProductCatalogUrl=http://productcatalog
#      - ProductCatalogUrl=http://private-05cc8-chapter2productcataloguemicroservice.apiary-mock.com
    ports:
      - "5000:80"

  sql.data:
    environment:
      - SA_PASSWORD=Pass@word
      - ACCEPT_EULA=Y
    ports:
      - "5433:1433"

  eventstore:
    ports:
      - "2113:2113"
      - "1113:1113"

  productcatalog:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
    ports:
      - "5001:80"
